using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DcmSharp.SourceGenerator
{
    [Generator]
    public class DicomTagsGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var provider = context.AdditionalTextsProvider
                .Collect()
                .Select((_, _) => DicomAttributesLoader.LoadAttributesFromZip());

            context.RegisterSourceOutput(provider, (spc, attributes) =>
            {
                if (attributes == null || attributes.Count == 0)
                {
                    return;
                }

                GenerateDicomTags(spc, attributes);
            });
        }


        private static void GenerateDicomTags(SourceProductionContext context, List<DicomAttribute> attributes)
        {
            var sourceBuilder = new StringBuilder();
            sourceBuilder.AppendLine("// <auto-generated/>");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine("using System;");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine("namespace DcmSharp;");
            sourceBuilder.AppendLine("");
            sourceBuilder.AppendLine("/// <summary>");
            sourceBuilder.AppendLine("/// DICOM tags from the DICOM standard.");
            sourceBuilder.AppendLine("/// </summary>");
            sourceBuilder.AppendLine("public static partial class DicomTags");
            sourceBuilder.AppendLine("{");

            var tags = new List<string>();
            foreach (var attr in attributes)
            {
                string? tag = attr.Tag;
                string? keyword = attr.Keyword;
                string? name = attr.Name;
                string[]? vrs = GetValueRepresentations(attr.ValueRepresentation);
                string? vm = GetValueMultiplicity(attr.ValueMultiplicity);

                if (string.IsNullOrEmpty(tag)
                    || string.IsNullOrEmpty(keyword)
                    || string.IsNullOrEmpty(name)
                    || vrs is null
                    || vm is null)
                {
                    continue;
                }

                // Parse the tag (0008,0005) to extract group and element
                string[] tagParts = tag!.Trim('(', ')').Split(',');
                if (tagParts.Length != 2)
                    continue;

                string group = tagParts[0].Trim().Replace("X", "0");
                string element = tagParts[1].Trim().Replace("X", "0");

                sourceBuilder.AppendLine($"    /// <summary>");
                sourceBuilder.AppendLine($"    /// {tag} {EscapeXmlComment(name!)}");
                foreach (string vr in vrs)
                {
                    sourceBuilder.AppendLine($"    /// VR: <see cref=\"DicomVR.{vr}\">{vr}</see>");
                }

                sourceBuilder.AppendLine($"    /// VM: <see cref=\"DicomVM.{vm}\">{attr.ValueMultiplicity}</see>");
                sourceBuilder.AppendLine($"    /// </summary>");
                if (string.Equals(attr.Retired, "Y", StringComparison.Ordinal))
                {
                    sourceBuilder.AppendLine($"    [Obsolete(\"This DICOM tag is retired.\")]");
                }
                sourceBuilder.Append($"    public static readonly DicomTag {keyword} = new DicomTag(");
                // Group
                sourceBuilder.Append($"0x{group}");
                // Element
                sourceBuilder.Append($", 0x{element}");
                // VR
                if (vrs.Length == 0)
                {
                    sourceBuilder.Append($", DicomVR.UN");
                }
                else
                {
                    sourceBuilder.Append($", DicomVR.{vrs[0]}");
                }
                // Additional VRs
                sourceBuilder.Append($", [ ");
                for (int index = 1; index < vrs.Length; index++)
                {
                    string vr = vrs[index];
                    sourceBuilder.Append($"DicomVR.{vr}");
                    if (index < vrs.Length - 1)
                    {
                        sourceBuilder.Append(", ");
                    }
                }
                sourceBuilder.Append($" ]");
                // VM
                sourceBuilder.Append($", DicomVM.{vm}");
                // Keyword
                sourceBuilder.Append($", \"{keyword}\"");
                // Name
                sourceBuilder.Append($", \"{name}\");");
                sourceBuilder.AppendLine();
                sourceBuilder.AppendLine();

                tags.Add(keyword!);
            }

            sourceBuilder.AppendLine("#pragma warning disable CS0618 // Type or member is obsolete");
            sourceBuilder.AppendLine("    /// <summary>");
            sourceBuilder.AppendLine("    /// An array containing all DICOM tags from the DICOM standard.");
            sourceBuilder.AppendLine("    /// </summary>");
            sourceBuilder.AppendLine("    public static readonly DicomTag[] All = [");
            foreach (string tag in tags)
            {
                sourceBuilder.AppendLine($"        {tag},");
            }

            sourceBuilder.AppendLine("    ];");
            sourceBuilder.AppendLine("#pragma warning restore CS0618 // Type or member is obsolete");
            sourceBuilder.AppendLine("");
            sourceBuilder.AppendLine("}");
            sourceBuilder.AppendLine("");

            context.AddSource("DicomTags.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
        }

        private static string EscapeXmlComment(string text)
        {
            if (string.IsNullOrEmpty(text))
                return text;

            return text
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("\"", "&quot;")
                .Replace("'", "&apos;");
        }

        private static string? GetValueMultiplicity(string? vm)
        {
            if (vm is null)
            {
                return null;
            }

            switch (vm)
            {
                case "1":
                    return "VM_1";
                case "1-2":
                    return "VM_1_2";
                case "1-3":
                    return "VM_1_3";
                case "1-8":
                    return "VM_1_8";
                case "1-32":
                    return "VM_1_32";
                case "1-99":
                    return "VM_1_99";
                case "1-n":
                    return "VM_1_n";
                case "2":
                    return "VM_2";
                case "2-n":
                    return "VM_2_n";
                case "2-2n":
                    return "VM_2_2n";
                case "3":
                    return "VM_3";
                case "3-n":
                    return "VM_3_n";
                case "3-3n":
                    return "VM_3_3n";
                case "4":
                    return "VM_4";
                case "4-n":
                    return "VM_4_n";
                case "6":
                    return "VM_6";
                case "6-n":
                    return "VM_6_n";
                case "9 ":
                    return "VM_9";
                case "16":
                    return "VM_16";
                case "Unknown ":
                    return "VM_U";
            }

            return null;
        }

        private static string[]? GetValueRepresentations(string? vr)
        {
            if (vr is null)
            {
                return null;
            }

            string[] split = vr.Split([" or "], StringSplitOptions.RemoveEmptyEntries);
            var vrs = new List<string>();
            foreach (string token in split)
            {
                switch (token)
                {
                    case "AE":
                        vrs.Add("AE");
                        break;
                    case "AS":
                        vrs.Add("AS");
                        break;
                    case "AT":
                        vrs.Add("AT");
                        break;
                    case "CS":
                        vrs.Add("CS");
                        break;
                    case "DA":
                        vrs.Add("DA");
                        break;
                    case "DS":
                        vrs.Add("DS");
                        break;
                    case "DT":
                        vrs.Add("DT");
                        break;
                    case "FL":
                        vrs.Add("FL");
                        break;
                    case "FD":
                        vrs.Add("FD");
                        break;
                    case "IS":
                        vrs.Add("IS");
                        break;
                    case "LO":
                        vrs.Add("LO");
                        break;
                    case "LT":
                        vrs.Add("LT");
                        break;
                    case "OB":
                        vrs.Add("OB");
                        break;
                    case "OD":
                        vrs.Add("OD");
                        break;
                    case "OF":
                        vrs.Add("OF");
                        break;
                    case "OL":
                        vrs.Add("OL");
                        break;
                    case "OW":
                        vrs.Add("OW");
                        break;
                    case "OV":
                        vrs.Add("OV");
                        break;
                    case "PN":
                        vrs.Add("PN");
                        break;
                    case "SH":
                        vrs.Add("SH");
                        break;
                    case "SL":
                        vrs.Add("SL");
                        break;
                    case "SQ":
                        vrs.Add("SQ");
                        break;
                    case "SS":
                        vrs.Add("SS");
                        break;
                    case "ST":
                        vrs.Add("ST");
                        break;
                    case "SV":
                        vrs.Add("SV");
                        break;
                    case "TM":
                        vrs.Add("TM");
                        break;
                    case "UC":
                        vrs.Add("UC");
                        break;
                    case "UI":
                        vrs.Add("UI");
                        break;
                    case "UL":
                        vrs.Add("UL");
                        break;
                    case "UN":
                        vrs.Add("UN");
                        break;
                    case "UR":
                        vrs.Add("UR");
                        break;
                    case "US":
                        vrs.Add("US");
                        break;
                    case "UT":
                        vrs.Add("UT");
                        break;
                    case "UV":
                        vrs.Add("UV");
                        break;
                }
            }

            return vrs.ToArray();
        }
    }
}
