name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Restore tools
      run: dotnet tool restore
    - name: Check formatting
      run: dotnet csharpier check .
    - name: Restore
      run: dotnet restore DcmSharp.CI.slnf
    - name: Build
      run: dotnet build DcmSharp.CI.slnf --configuration Release --no-restore
    - name: Test
      run: dotnet test DcmSharp.CI.slnf --configuration Release --no-restore --verbosity normal
