name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.x
          10.x
    - name: Restore
      run: dotnet restore DcmSharp.CI.slnf
    - name: Build
      run: dotnet build DcmSharp.CI.slnf --configuration Release --no-restore
    - name: Test
      run: dotnet test DcmSharp.CI.slnf --configuration Release --no-restore --verbosity normal
