name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        dotnet test tests/DcmSharp.Tests/ --configuration Release --no-restore --verbosity normal
        dotnet test tests/DcmAnonymize.Tests/ --configuration Release --no-restore --verbosity normal
        dotnet test tests/DcmOrganize.Tests/ --configuration Release --no-restore --verbosity normal
        dotnet test tests/DcmSharp.SourceGenerator.Tests/ --configuration Release --no-restore --verbosity normal
